# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/DeviceMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/DeviceMessages.proto',
  package='textsecure',
  serialized_pb=_b('\n\x1bprotos/DeviceMessages.proto\x12\ntextsecure\" \n\x10ProvisioningUuid\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"4\n\x11ProvisionEnvelope\x12\x11\n\tpublicKey\x18\x01 \x01(\x0c\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\"X\n\x10ProvisionMessage\x12\x1a\n\x12identityKeyPrivate\x18\x02 \x01(\x0c\x12\x0e\n\x06number\x18\x03 \x01(\t\x12\x18\n\x10provisioningCode\x18\x04 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROVISIONINGUUID = _descriptor.Descriptor(
  name='ProvisioningUuid',
  full_name='textsecure.ProvisioningUuid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='textsecure.ProvisioningUuid.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=75,
)


_PROVISIONENVELOPE = _descriptor.Descriptor(
  name='ProvisionEnvelope',
  full_name='textsecure.ProvisionEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='publicKey', full_name='textsecure.ProvisionEnvelope.publicKey', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='textsecure.ProvisionEnvelope.body', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=129,
)


_PROVISIONMESSAGE = _descriptor.Descriptor(
  name='ProvisionMessage',
  full_name='textsecure.ProvisionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identityKeyPrivate', full_name='textsecure.ProvisionMessage.identityKeyPrivate', index=0,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number', full_name='textsecure.ProvisionMessage.number', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='provisioningCode', full_name='textsecure.ProvisionMessage.provisioningCode', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=219,
)

DESCRIPTOR.message_types_by_name['ProvisioningUuid'] = _PROVISIONINGUUID
DESCRIPTOR.message_types_by_name['ProvisionEnvelope'] = _PROVISIONENVELOPE
DESCRIPTOR.message_types_by_name['ProvisionMessage'] = _PROVISIONMESSAGE

ProvisioningUuid = _reflection.GeneratedProtocolMessageType('ProvisioningUuid', (_message.Message,), dict(
  DESCRIPTOR = _PROVISIONINGUUID,
  __module__ = 'protos.DeviceMessages_pb2'
  # @@protoc_insertion_point(class_scope:textsecure.ProvisioningUuid)
  ))
_sym_db.RegisterMessage(ProvisioningUuid)

ProvisionEnvelope = _reflection.GeneratedProtocolMessageType('ProvisionEnvelope', (_message.Message,), dict(
  DESCRIPTOR = _PROVISIONENVELOPE,
  __module__ = 'protos.DeviceMessages_pb2'
  # @@protoc_insertion_point(class_scope:textsecure.ProvisionEnvelope)
  ))
_sym_db.RegisterMessage(ProvisionEnvelope)

ProvisionMessage = _reflection.GeneratedProtocolMessageType('ProvisionMessage', (_message.Message,), dict(
  DESCRIPTOR = _PROVISIONMESSAGE,
  __module__ = 'protos.DeviceMessages_pb2'
  # @@protoc_insertion_point(class_scope:textsecure.ProvisionMessage)
  ))
_sym_db.RegisterMessage(ProvisionMessage)


# @@protoc_insertion_point(module_scope)
